### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by daniktheboss** [nosix/PyCraft#2]
Hello, I wanted to ask, can we work in this project? I need help updating the packets and protocols. Please if you can do that that would be awesome.

**Comment by haniokasai** [comment]
@nosix  does not look active on github,so i think you can contact him better in twitter. https://twitter.com/i_nosix

**Comment by nosix** [comment]
Hello.

You can freely modify this project.

This project began in order for me to learn Python. It's my first Python project. So, I think it is difficult to read the source code. Furthermore, I am not familiar with Minecraft. It is not advisable to extend this project, but please use it if it is useful.

I can't help updating. I have no time. 

If you want to update protocols, I think that you will change mainly the following source code.

PyCraft/src/pycraft/network/packet

Please see https://github.com/nosix/PyCraft/wiki.
